highlighter: pygments
markdown: redcarpet
redcarpet:
  extensions:
    - hard_wrap
    - no_intra_emphasis
    - autolink
    - strikethrough
    - fenced_code_blocks
permalink: pretty

name: George Stathis
url: http://george-stathis.com
description: 'General commentary on writing software, taming the web and personal interests.'
twitter: gstathis
github: gpstathis
gravatar_url: http://gravatar.com/avatar/ba71ad856b0e8d5f224b8c927c85a7c4
ga: 'UA-7528444-1'
