name: George Stathis
description: "General commentary on writing software, taming the web and personal interests"
meta_description: "General commentary on writing software, taming the web and personal interests."

markdown: kramdown
highlighter: rouge
# permalink: pretty
# permalink: /:categories/:title/
permalink: /:year/:month/:day/:title/
excerpt_separator: <!--more-->
logo: false
paginate: 15
baseurl: '/'
domain_name: 'http://george-stathis.com'
google_analytics: 'UA-7528444-1'
gems:
  - jekyll-paginate
  - jekyll-redirect-from
exclude:
  - Gemfile
  - Gemfile.lock

# Details for the RSS feed generator
url:            '/'
author:         'George Stathis'
